sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kansodocker/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  kansodocker/client npm run test

after_sucess:
  - docker build -t kansodocker/multi-client ./client
  - docker build -t kansodocker/multi-nginx ./nginx
  - docker build -t kansodocker/multi-server ./server
  - docker build -t kansodocker/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push kansodocker/multi-client
  - docker push kansodocker/multi-nginx
  - docker push kansodocker/multi-server
  - docker push kansodocker/multi-worker
