sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kansodocker/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  kansodocker/client npm run test

after_sucess:
  - docker build -t kansodocker/multi-client ./client
  - docker build -t kansodocker/multi-nginx ./nginx
  - docker build -t kansodocker/multi-server ./server
  - docker build -t kansodocker/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kansodocker/multi-client
  - docker push kansodocker/multi-nginx
  - docker push kansodocker/multi-server
  - docker push kansodocker/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-209042061618"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY