version: '3'
services:
  postgres:
    restart: always
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  apiserver:
    env_file:
      - ./server/config/dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    env_file:
      - ./worker/config/dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  httpd:
    depends_on:
      - apiserver
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./httpd
    ports:
      - '3050:80'
